const { withAppBuildGradle } = require('@expo/config-plugins');

// Puriki 1.0 ships direct APK downloads (GitHub Releases / website), not a
// single Google Play AAB, so per-ABI APKs are generated from one Gradle
// build via `splits.abi`, with a universal APK kept as a compatibility
// fallback. This matches the default `reactNativeArchitectures` already set
// by the Expo/React Native template (see android/gradle.properties).
const ABIS = ['armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'];

const BLOCK_START = '    // @generated begin puriki-abi-splits';
const BLOCK_END = '    // @generated end puriki-abi-splits';

function buildAbiSplitBlock() {
  const include = ABIS.map((abi) => `"${abi}"`).join(', ');
  return [
    BLOCK_START,
    '    splits {',
    '        abi {',
    '            enable true',
    '            reset()',
    `            include ${include}`,
    '            universalApk true',
    '        }',
    '    }',
    BLOCK_END,
  ].join('\n');
}

const ANDROID_BLOCK_ANCHOR = /android\s*\{/;

function applyAbiSplits(contents) {
  if (contents.includes(BLOCK_START)) {
    // Already applied by a previous prebuild; keep it idempotent.
    return contents;
  }

  if (!ANDROID_BLOCK_ANCHOR.test(contents)) {
    throw new Error(
      "withAndroidAbiSplits: could not find the 'android {' block in " +
        'app/build.gradle. The Expo/React Native Gradle template may have ' +
        'changed in a way this plugin does not expect; update the plugin ' +
        'instead of silently skipping ABI splits.',
    );
  }

  return contents.replace(
    ANDROID_BLOCK_ANCHOR,
    (match) => `${match}\n${buildAbiSplitBlock()}\n`,
  );
}

function withAndroidAbiSplits(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        'withAndroidAbiSplits only supports the Groovy app/build.gradle ' +
          'generated by Expo prebuild.',
      );
    }

    config.modResults.contents = applyAbiSplits(config.modResults.contents);
    return config;
  });
}

module.exports = withAndroidAbiSplits;
module.exports.applyAbiSplits = applyAbiSplits;
module.exports.ABIS = ABIS;
